CREATE TYPE user_status AS ENUM ('ACTIVE', 'BANNED');
CREATE TYPE gender_type AS ENUM ('MALE', 'FEMALE', 'OTHER');
CREATE TYPE role_type AS ENUM ('GUEST', 'ADMIN');
CREATE TYPE media_type_enum AS ENUM ('IMAGE', 'VIDEO');
CREATE TYPE provider_type AS ENUM ('GOOGLE');
CREATE TYPE post_status AS ENUM ('PUBLIC', 'ARCHIVED', 'BANNED');
CREATE TYPE role_conversation AS ENUM ('MEMBER', 'ADMIN');
CREATE TYPE conversation_type AS ENUM ('PRIVATE', 'GROUP');

-- INDEXES
CREATE INDEX idx_user_fullname_lower ON users (LOWER(full_name));
CREATE INDEX idx_posts_title_lower ON posts (LOWER(title));

-- TABLES
CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    role role_type,
    username VARCHAR(50) UNIQUE,
    password VARCHAR(255),
    email VARCHAR(100) UNIQUE,
    full_name VARCHAR(100),
    gender gender_type,
    dob DATE,
    status user_status NOT NULL DEFAULT 'ACTIVE',
    avatar_id BIGINT REFERENCES media(id) ON DELETE SET NULL,
    cover_id BIGINT REFERENCES media(id) ON DELETE SET NULL,
    google_id VARCHAR(255) UNIQUE,
    follower_count BIGINT NOT NULL DEFAULT 0, -- nguoi ma theo doi minh
    following_count BIGINT NOT NULL DEFAULT 0, -- nguoi ma minh thoi doi
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);
CREATE TABLE admin (
    id BIGSERIAL PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE

);
CREATE TABLE guest (
    id BIGSERIAL PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url TEXT NOT NULL,
    type media_type_enum NOT NULL,
    cloud_name TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE user_oauth_tokens (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    provider provider_type NOT NULL DEFAULT 'GOOGLE',
    access_token TEXT,
    refresh_token TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);

CREATE TABLE posts (
    id         BIGSERIAL PRIMARY KEY,
    user_id    BIGINT REFERENCES users (id) ON DELETE CASCADE,
    title VARCHAR () NOT NULL DEFAULT 'Untitled Post',
    content    TEXT             NOT NULL,
    status     post_status NOT NULL DEFAULT 'PUBLIC',
    folder_id  UUID NOT NULL,
    created_at TIMESTAMPTZ               DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);

CREATE TABLE media_posts (
    media_id BIGINT REFERENCES media(id) ON DELETE CASCADE,
    post_id BIGINT REFERENCES posts(id) ON DELETE CASCADE,
    PRIMARY KEY (media_id, post_id)
);

CREATE TABLE comment (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    post_id BIGINT REFERENCES posts(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    level INT NOT NULL DEFAULT 0 CHECK ( level >= 0 and level <= 2 ),
    parent_comment_id BIGINT REFERENCES comment(id),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);

CREATE TABLE media_comment (
    media_id BIGINT REFERENCES media(id) ON DELETE CASCADE,
    comment_id BIGINT REFERENCES comment(id) ON DELETE CASCADE,
    PRIMARY KEY (media_id, comment_id)
);

CREATE TABLE follow (
    follower_id BIGINT REFERENCES users(id) ON DELETE CASCADE, -- ban than nguoi theo doi
    following_id BIGINT REFERENCES users(id) ON DELETE CASCADE, -- nguoi duoc theo doi
    created_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (follower_id, following_id)
);

CREATE TABLE conversation (
    id BIGSERIAL PRIMARY KEY,
    group_name VARCHAR(255),
    group_avatar_id BIGINT REFERENCES media(id) ON DELETE SET NULL,
    type conversation_type NOT NULL DEFAULT 'PRIVATE',
    last_message_at TIMESTAMPTZ DEFAULT NOW(),
    last_message_content TEXT,
    last_message_sender_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
);

CREATE TABLE conversation_members (
    conversation_id BIGINT REFERENCES conversation(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    role role_conversation NOT NULL DEFAULT 'MEMBER',
    joined_at TIMESTAMPTZ DEFAULT NOW(),
    cleared_at TIMESTAMPTZ DEFAULT NULL,
    PRIMARY KEY (conversation_id, user_id)
);

CREATE TABLE message (
    id BIGSERIAL PRIMARY KEY,
    conversation_id BIGINT REFERENCES conversation(id) ON DELETE CASCADE,
    sender_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    content TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

CREATE TABLE media_message (
    media_id BIGINT REFERENCES media(id) ON DELETE CASCADE,
    message_id BIGINT REFERENCES message(id) ON DELETE CASCADE,
    PRIMARY KEY (media_id, message_id)
);